### ISSUE TITLE
Confusing Range Difference in Detection and Error Logging

### ISSUE THREAD

**Issue by myche** [sbn-psi/data-provider-tools#3]
The code actually appears correct for checking that vector commands place coordinates within signed 16-bit integers

https://github.com/sbn-psi/data-provider-tools/blob/1e1a6692757ddbe1981cc649d04d15258c83dce8/pdftweaks/remove_out_of_range_strokes.py#L32

However, the error one receives from VeraPDF states the following:

```Absolute real value must be less than or equal to 32767.0```

Implying that they might be checking a slightly different range (+/- 32767.0).  Dunno why?

I might try to create a PDF with such edge-case command coordinates to see if this matters to VeraPDF.

Just thought I'd capture this somewhere ;-)

**Comment by jstone-psi** [comment]
This comes from table C1 in the PDF reference version 1.4.

I'll update the script to conform to this
